
import { LanguageCode, Translations } from './languageTypes';

export const languages = [
  { code: 'en' as LanguageCode, name: 'English' },
  { code: 'ru' as LanguageCode, name: 'Русский' },
  { code: 'uk' as LanguageCode, name: 'Українська' },
  { code: 'zh' as LanguageCode, name: '中文' },
  { code: 'de' as LanguageCode, name: 'Deutsch' },
  { code: 'ja' as LanguageCode, name: '日本語' },
  { code: 'fr' as LanguageCode, name: 'Français' }
];

export const defaultTranslations: Record<LanguageCode, Translations> = {
  fr: {
    guide: 'Guide',
    guideLocal: 'Guide',
    privacy: 'Confidentialité',
    changelogs: 'Journaux des modifications',
    blogs: 'Blogs',
    download: 'Télécharger',
    github: 'GitHub',
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    downloadNow: 'Télécharger maintenant',
    changeLanguage: 'Changer de langue',
    githubRepo: 'Dépôt GitHub',
    discordServer: 'Serveur Discord',
    selectLanguage: 'Sélectionner la langue',
    language: 'fr',
    about: 'À propos',
    contact: 'Contact',
    contactUs: 'Contactez-nous',
    email: 'Email',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Nous soutenir',
    joinCommunity: 'Rejoindre la communauté',
    communityPlatforms: 'Plateformes communautaires',
    resources: 'Ressources',
    support: 'Support',
    documentation: 'Documentation',
    blogPosts: 'Articles de blog',
    privacyPolicy: 'Politique de confidentialité',
    error404: '404 - Page non trouvée',
    pageNotFound: 'La page que vous recherchez n\'existe pas.',
    backToHome: 'Retour à l\'accueil',
    homeMessage: 'Retourner à la page d\'accueil',
    search: 'Rechercher',
    submit: 'Soumettre',
    reportBug: 'Signaler un bug',
    testing: 'Test',
    issues: 'Problèmes',
    latestBuilds: 'Dernières versions',
    deployRelease: 'Déployer la version',
    validate: 'Valider',
    build: 'Construire',
    branch: 'Branche',
    updated: 'Mis à jour',
    news: 'Actualités',
    readMore: 'Lire la suite',
    appearanceGuide: 'Guide d\'apparence',
    underConstruction: 'En construction...',
    colorPaletteThemes: 'Palette de couleurs et thèmes',
    tip: 'ASTUCE',
    cardColor: 'Couleur de carte',
    topBarColor: 'Couleur de la barre supérieure',
    sidebarColor: 'Couleur de la barre latérale',
    backgroundColor: 'Couleur d\'arrière-plan',
    basicComponentHighlight: 'Couleur de surbrillance des composants de base',
    errorColor: 'Couleur d\'erreur',
    features: 'Fonctionnalités',
    advanced: 'Avancées',
    powerful: 'Puissantes',
    modern: 'Modernes',
    crossPlatform: 'Multi-plateformes',
    openSource: 'Open Source',
    // GitHub File Viewer translations
    viewCode: 'Voir le code',
    sortBy: 'Trier par',
    sortByName: 'Nom',
    sortByDate: 'Date',
    ascending: 'Croissant',
    descending: 'Décroissant',
    parentDirectory: 'Dossier parent',
    fileExplorer: 'Explorateur de fichiers',
    noFileSelected: 'Aucun fichier sélectionné',
    selectFileToView: 'Sélectionnez un fichier pour afficher son contenu',
    loading: 'Chargement...',
    copy: 'Copier',
    copied: 'Copié',
    downloadFile: 'Télécharger'
  },
  en: {
    guide: 'Guide',
    guideLocal: 'Guide',
    privacy: 'Privacy',
    changelogs: 'Changelogs',
    blogs: 'Blogs',
    download: 'Download',
    github: 'GitHub',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    downloadNow: 'Download Now',
    changeLanguage: 'Change Language',
    githubRepo: 'GitHub Repository',
    discordServer: 'Discord Server',
    selectLanguage: 'Select Language',
    language: 'en',
    about: 'About',
    contact: 'Contact',
    contactUs: 'Contact Us',
    email: 'Email',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Support Us',
    joinCommunity: 'Join Community',
    communityPlatforms: 'Community Platforms',
    resources: 'Resources',
    support: 'Support',
    documentation: 'Documentation',
    blogPosts: 'Blog Posts',
    privacyPolicy: 'Privacy Policy',
    error404: '404 - Page Not Found',
    pageNotFound: 'The page you are looking for does not exist.',
    backToHome: 'Back to Home',
    homeMessage: 'Go back to the homepage',
    search: 'Search',
    submit: 'Submit',
    reportBug: 'Report Bug',
    testing: 'Testing',
    issues: 'Issues',
    latestBuilds: 'Latest Builds',
    deployRelease: 'Deploy Release',
    validate: 'Validate',
    build: 'Build',
    branch: 'Branch',
    updated: 'Updated',
    news: 'News',
    readMore: 'Read more',
    appearanceGuide: 'Appearance Guide',
    underConstruction: 'Under Construction...',
    colorPaletteThemes: 'Color Palette and Themes',
    tip: 'TIP',
    cardColor: 'Card color',
    topBarColor: 'Top bar color',
    sidebarColor: 'Sidebar color',
    backgroundColor: 'Background color',
    basicComponentHighlight: 'Basic component highlight color',
    errorColor: 'Error color',
    features: 'Features',
    advanced: 'Advanced',
    powerful: 'Powerful',
    modern: 'Modern',
    crossPlatform: 'Cross-Platform',
    openSource: 'Open Source',
    // GitHub File Viewer translations
    viewCode: 'View Code',
    sortBy: 'Sort by',
    sortByName: 'Name',
    sortByDate: 'Date',
    ascending: 'Ascending',
    descending: 'Descending',
    parentDirectory: 'Parent Directory',
    fileExplorer: 'File Explorer',
    noFileSelected: 'No file selected',
    selectFileToView: 'Select a file to view its content',
    loading: 'Loading...',
    copy: 'Copy',
    copied: 'Copied',
    downloadFile: 'Download'
  },
  ru: {
    guide: 'Руководство',
    guideLocal: 'Руководство',
    privacy: 'Конфиденциальность',
    changelogs: 'Список изменений',
    blogs: 'Блоги',
    download: 'Скачать',
    github: 'GitHub',
    darkMode: 'Темная тема',
    lightMode: 'Светлая тема',
    downloadNow: 'Скачать сейчас',
    changeLanguage: 'Изменить язык',
    githubRepo: 'GitHub Репозиторий',
    discordServer: 'Discord Сервер',
    selectLanguage: 'Выберите язык',
    language: 'ru',
    about: 'О проекте',
    contact: 'Контакты',
    contactUs: 'Связаться с нами',
    email: 'Электронная почта',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Поддержать нас',
    joinCommunity: 'Присоединиться к сообществу',
    communityPlatforms: 'Платформы сообщества',
    resources: 'Ресурсы',
    support: 'Поддержка',
    documentation: 'Документация',
    blogPosts: 'Статьи блога',
    privacyPolicy: 'Политика конфиденциальности',
    error404: '404 - Страница не найдена',
    pageNotFound: 'Страница, которую вы ищете, не существует.',
    backToHome: 'Вернуться на главную',
    homeMessage: 'Вернуться на главную страницу',
    search: 'Поиск',
    submit: 'Отправить',
    reportBug: 'Сообщить об ошибке',
    testing: 'Тестирование',
    issues: 'Проблемы',
    latestBuilds: 'Последние сборки',
    deployRelease: 'Развернуть релиз',
    validate: 'Проверить',
    build: 'Сборка',
    branch: 'Ветка',
    updated: 'Обновлено',
    news: 'Новости',
    readMore: 'Читать далее',
    appearanceGuide: 'Руководство по внешнему виду',
    underConstruction: 'В разработке...',
    colorPaletteThemes: 'Цветовая палитра и темы',
    tip: 'СОВЕТ',
    cardColor: 'Цвет карточек',
    topBarColor: 'Цвет верхней панели',
    sidebarColor: 'Цвет боковой панели',
    backgroundColor: 'Цвет фона',
    basicComponentHighlight: 'Цвет подсветки базовых компонентов',
    errorColor: 'Цвет ошибок',
    features: 'Возможности',
    advanced: 'Продвинутые',
    powerful: 'Мощные',
    modern: 'Современные',
    crossPlatform: 'Кроссплатформенные',
    openSource: 'Открытый исходный код',
    // GitHub File Viewer translations
    viewCode: 'Просмотр кода',
    sortBy: 'Сортировать по',
    sortByName: 'Имени',
    sortByDate: 'Дате',
    ascending: 'По возрастанию',
    descending: 'По убыванию',
    parentDirectory: 'Родительская директория',
    fileExplorer: 'Проводник',
    noFileSelected: 'Файл не выбран',
    selectFileToView: 'Выберите файл для просмотра содержимого',
    loading: 'Загрузка...',
    copy: 'Копировать',
    copied: 'Скопировано',
    downloadFile: 'Скачать'
  },
  uk: {
    guide: 'Керівництво',
    guideLocal: 'Керівництво',
    privacy: 'Конфіденційність',
    changelogs: 'Список змін',
    blogs: 'Блоги',
    download: 'Завантажити',
    github: 'GitHub',
    darkMode: 'Темна тема',
    lightMode: 'Світла тема',
    downloadNow: 'Завантажити зараз',
    changeLanguage: 'Змінити мову',
    githubRepo: 'GitHub Репозиторій',
    discordServer: 'Discord Сервер',
    selectLanguage: 'Виберіть мову',
    language: 'uk',
    about: 'Про проект',
    contact: 'Контакти',
    contactUs: 'Зв\'язатися з нами',
    email: 'Електронна пошта',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Підтримати нас',
    joinCommunity: 'Приєднатися до спільноти',
    communityPlatforms: 'Платформи спільноти',
    resources: 'Ресурси',
    support: 'Підтримка',
    documentation: 'Документація',
    blogPosts: 'Статті блогу',
    privacyPolicy: 'Політика конфіденційності',
    error404: '404 - Сторінка не знайдена',
    pageNotFound: 'Сторінка, яку ви шукаєте, не існує.',
    backToHome: 'Повернутися додому',
    homeMessage: 'Повернутися на головну сторінку',
    search: 'Пошук',
    submit: 'Відправити',
    reportBug: 'Повідомити про помилку',
    testing: 'Тестування',
    issues: 'Проблеми',
    latestBuilds: 'Останні збірки',
    deployRelease: 'Розгорнути реліз',
    validate: 'Перевірити',
    build: 'Збірка',
    branch: 'Гілка',
    updated: 'Оновлено',
    news: 'Новини',
    readMore: 'Читати далі',
    appearanceGuide: 'Керівництво по зовнішньому вигляду',
    underConstruction: 'В розробці...',
    colorPaletteThemes: 'Кольорова палітра та теми',
    tip: 'ПОРАДА',
    cardColor: 'Колір карток',
    topBarColor: 'Колір верхньої панелі',
    sidebarColor: 'Колір бічної панелі',
    backgroundColor: 'Колір фону',
    basicComponentHighlight: 'Колір підсвітки базових компонентів',
    errorColor: 'Колір помилок',
    features: 'Можливості',
    advanced: 'Розширені',
    powerful: 'Потужні',
    modern: 'Сучасні',
    crossPlatform: 'Кросплатформні',
    openSource: 'Відкритий вихідний код',
    // GitHub File Viewer translations
    viewCode: 'Перегляд коду',
    sortBy: 'Сортувати за',
    sortByName: 'Ім\'ям',
    sortByDate: 'Датою',
    ascending: 'За зростанням',
    descending: 'За спаданням',
    parentDirectory: 'Батьківська директорія',
    fileExplorer: 'Провідник',
    noFileSelected: 'Файл не вибрано',
    selectFileToView: 'Виберіть файл для перегляду вмісту',
    loading: 'Завантаження...',
    copy: 'Копіювати',
    copied: 'Скопійовано',
    downloadFile: 'Завантажити'
  },
  zh: {
    guide: '指南',
    guideLocal: '指南',
    privacy: '隐私',
    changelogs: '更新日志',
    blogs: '博客',
    download: '下载',
    github: 'GitHub',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    downloadNow: '立即下载',
    changeLanguage: '更改语言',
    githubRepo: 'GitHub 仓库',
    discordServer: 'Discord 服务器',
    selectLanguage: '选择语言',
    language: 'zh',
    about: '关于项目',
    contact: '联系',
    contactUs: '联系我们',
    email: '邮箱',
    patreon: 'Patreon',
    afdian: '爱发电',
    kook: 'Kook',
    supportUs: '支持我们',
    joinCommunity: '加入社区',
    communityPlatforms: '社区平台',
    resources: '资源',
    support: '支持',
    documentation: '文档',
    blogPosts: '博客文章',
    privacyPolicy: '隐私政策',
    error404: '404 - 页面未找到',
    pageNotFound: '您要查找的页面不存在。',
    backToHome: '返回首页',
    homeMessage: '返回主页',
    search: '搜索',
    submit: '提交',
    reportBug: '报告错误',
    testing: '测试',
    issues: '问题',
    latestBuilds: '最新构建',
    deployRelease: '部署发布',
    validate: '验证',
    build: '构建',
    branch: '分支',
    updated: '更新于',
    news: '新闻',
    readMore: '阅读更多',
    appearanceGuide: '外观指南',
    underConstruction: '建设中...',
    colorPaletteThemes: '调色板和主题',
    tip: '提示',
    cardColor: '卡片颜色',
    topBarColor: '顶部栏颜色',
    sidebarColor: '侧边栏颜色',
    backgroundColor: '背景颜色',
    basicComponentHighlight: '基本组件高亮颜色',
    errorColor: '错误颜色',
    features: '功能',
    advanced: '高级',
    powerful: '强大',
    modern: '现代',
    crossPlatform: '跨平台',
    openSource: '开源',
    // GitHub File Viewer translations
    viewCode: '查看代码',
    sortBy: '排序方式',
    sortByName: '名称',
    sortByDate: '日期',
    ascending: '升序',
    descending: '降序',
    parentDirectory: '上级目录',
    fileExplorer: '文件浏览器',
    noFileSelected: '未选择文件',
    selectFileToView: '选择一个文件查看其内容',
    loading: '加载中...',
    copy: '复制',
    copied: '已复制',
    downloadFile: '下载'
  },
  de: {
    guide: 'Anleitung',
    guideLocal: 'Anleitung',
    privacy: 'Datenschutz',
    changelogs: 'Änderungsprotokoll',
    blogs: 'Blogs',
    download: 'Herunterladen',
    github: 'GitHub',
    darkMode: 'Dunkler Modus',
    lightMode: 'Heller Modus',
    downloadNow: 'Jetzt herunterladen',
    changeLanguage: 'Sprache ändern',
    githubRepo: 'GitHub Repository',
    discordServer: 'Discord Server',
    selectLanguage: 'Sprache auswählen',
    language: 'de',
    about: 'Über das Projekt',
    contact: 'Kontakt',
    contactUs: 'Kontaktieren Sie uns',
    email: 'E-Mail',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Unterstützen Sie uns',
    joinCommunity: 'Der Gemeinschaft beitreten',
    communityPlatforms: 'Community-Plattformen',
    resources: 'Ressourcen',
    support: 'Unterstützung',
    documentation: 'Dokumentation',
    blogPosts: 'Blog-Beiträge',
    privacyPolicy: 'Datenschutzrichtlinie',
    error404: '404 - Seite nicht gefunden',
    pageNotFound: 'Die Seite, die Sie suchen, existiert nicht.',
    backToHome: 'Zurück zur Startseite',
    homeMessage: 'Zurück zur Hauptseite',
    search: 'Suchen',
    submit: 'Senden',
    reportBug: 'Fehler melden',
    testing: 'Testen',
    issues: 'Probleme',
    latestBuilds: 'Neueste Builds',
    deployRelease: 'Release bereitstellen',
    validate: 'Validieren',
    build: 'Build',
    branch: 'Branch',
    updated: 'Aktualisiert',
    news: 'Nachrichten',
    readMore: 'Weiterlesen',
    appearanceGuide: 'Erscheinungsbildleitfaden',
    underConstruction: 'Im Aufbau...',
    colorPaletteThemes: 'Farbpalette und Themen',
    tip: 'TIPP',
    cardColor: 'Kartenfarbe',
    topBarColor: 'Farbe der oberen Leiste',
    sidebarColor: 'Seitenleistenfarbe',
    backgroundColor: 'Hintergrundfarbe',
    basicComponentHighlight: 'Grundkomponenten-Hervorhebungsfarbe',
    errorColor: 'Fehlerfarbe',
    features: 'Funktionen',
    advanced: 'Erweitert',
    powerful: 'Leistungsstark',
    modern: 'Modern',
    crossPlatform: 'Plattformübergreifend',
    openSource: 'Open Source',
    // GitHub File Viewer translations
    viewCode: 'Code anzeigen',
    sortBy: 'Sortieren nach',
    sortByName: 'Name',
    sortByDate: 'Datum',
    ascending: 'Aufsteigend',
    descending: 'Absteigend',
    parentDirectory: 'Übergeordnetes Verzeichnis',
    fileExplorer: 'Datei-Explorer',
    noFileSelected: 'Keine Datei ausgewählt',
    selectFileToView: 'Wählen Sie eine Datei aus, um ihren Inhalt anzuzeigen',
    loading: 'Wird geladen...',
    copy: 'Kopieren',
    copied: 'Kopiert',
    downloadFile: 'Herunterladen'
  },
  ja: {
    guide: 'ガイド',
    guideLocal: 'ガイド',
    privacy: 'プライバシー',
    changelogs: '変更履歴',
    blogs: 'ブログ',
    download: 'ダウンロード',
    github: 'GitHub',
    darkMode: 'ダークモード',
    lightMode: 'ライトモード',
    downloadNow: '今すぐダウンロード',
    changeLanguage: '言語を変更',
    githubRepo: 'GitHub リポジトリ',
    discordServer: 'Discord サーバー',
    selectLanguage: '言語を選択',
    language: 'ja',
    about: 'プロジェクトについて',
    contact: '連絡先',
    contactUs: 'お問い合わせ',
    email: 'メール',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'サポート',
    joinCommunity: 'コミュニティに参加',
    communityPlatforms: 'コミュニティプラットフォーム',
    resources: 'リソース',
    support: 'サポート',
    documentation: 'ドキュメント',
    blogPosts: 'ブログ投稿',
    privacyPolicy: 'プライバシーポリシー',
    error404: '404 - ページが見つかりません',
    pageNotFound: 'お探しのページは存在しません。',
    backToHome: 'ホームに戻る',
    homeMessage: 'ホームページに戻る',
    search: '検索',
    submit: '送信',
    reportBug: 'バグを報告',
    testing: 'テスト',
    issues: '問題',
    latestBuilds: '最新ビルド',
    deployRelease: 'リリースをデプロイ',
    validate: '検証',
    build: 'ビルド',
    branch: 'ブランチ',
    updated: '更新済み',
    news: 'ニュース',
    readMore: '続きを読む',
    appearanceGuide: '外観ガイド',
    underConstruction: '工事中...',
    colorPaletteThemes: 'カラーパレットとテーマ',
    tip: 'ヒント',
    cardColor: 'カードの色',
    topBarColor: 'トップバーの色',
    sidebarColor: 'サイドバーの色',
    backgroundColor: '背景色',
    basicComponentHighlight: '基本コンポーネントのハイライト色',
    errorColor: 'エラーカラー',
    features: '機能',
    advanced: '高度な',
    powerful: '強力な',
    modern: 'モダンな',
    crossPlatform: 'クロスプラットフォーム',
    openSource: 'オープンソース',
    // GitHub File Viewer translations
    viewCode: 'コードを表示',
    sortBy: '並び替え',
    sortByName: '名前',
    sortByDate: '日付',
    ascending: '昇順',
    descending: '降順',
    parentDirectory: '親ディレクトリ',
    fileExplorer: 'ファイルエクスプローラー',
    noFileSelected: 'ファイルが選択されていません',
    selectFileToView: 'ファイルを選択して内容を表示',
    loading: '読み込み中...',
    copy: 'コピー',
    copied: 'コピーしました',
    downloadFile: 'ダウンロード'
  }
};
