
import { LanguageCode, Translations } from './languageTypes';

export const languages = [
  { code: 'en', name: 'English' },
  { code: 'ru', name: 'Русский' },
  { code: 'uk', name: 'Українська' },
  { code: 'zh', name: '中文' },
  { code: 'de', name: 'Deutsch' },
  { code: 'ja', name: '日本語' }
];

export const defaultTranslations: Record<LanguageCode, Translations> = {
  en: {
    guide: 'Documentation',
    guideLocal: 'Guide',
    privacy: 'Privacy Policy',
    changelogs: 'Changelogs',
    blogs: 'Blog',
    download: 'Download',
    github: 'GitHub',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    downloadNow: 'Download Now',
    changeLanguage: 'Change Language',
    githubRepo: 'GitHub Repository',
    discordServer: 'Discord Server',
    selectLanguage: 'Select Language',
    language: 'Language',
    about: 'About',
    contact: 'Contact',
    contactUs: 'Contact Us',
    email: 'Email',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Support Us',
    joinCommunity: 'Join our Community',
    communityPlatforms: 'Community Platforms',
    resources: 'Resources',
    support: 'Support',
    documentation: 'Documentation',
    blogPosts: 'Blog Posts',
    privacyPolicy: 'Privacy Policy',
    error404: '404 Error',
    pageNotFound: 'Page Not Found',
    backToHome: 'Back to Home',
    homeMessage: 'Sorry, the page you are looking for does not exist.',
    search: 'Search',
    submit: 'Submit'
  },
  ru: {
    guide: 'Документация',
    guideLocal: 'Гид',
    privacy: 'Конфиденциальность',
    changelogs: 'История изменений',
    blogs: 'Блог',
    download: 'Скачать',
    github: 'GitHub',
    darkMode: 'Тёмная тема',
    lightMode: 'Светлая тема',
    downloadNow: 'Скачать сейчас',
    changeLanguage: 'Изменить язык',
    githubRepo: 'GitHub Репозиторий',
    discordServer: 'Discord Сервер',
    selectLanguage: 'Выберите язык',
    language: 'Язык',
    about: 'О нас',
    contact: 'Контакты',
    contactUs: 'Связаться с нами',
    email: 'Электронная почта',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Поддержать нас',
    joinCommunity: 'Присоединиться к сообществу',
    communityPlatforms: 'Платформы сообщества',
    resources: 'Ресурсы',
    support: 'Поддержка',
    documentation: 'Документация',
    blogPosts: 'Записи блога',
    privacyPolicy: 'Политика конфиденциальности',
    error404: 'Ошибка 404',
    pageNotFound: 'Страница не найдена',
    backToHome: 'Вернуться на главную',
    homeMessage: 'Извините, страница, которую вы ищете, не существует.',
    search: 'Поиск',
    submit: 'Отправить'
  },
  uk: {
    guide: 'Документація',
    guideLocal: 'Гід',
    privacy: 'Конфіденційність',
    changelogs: 'Історія змін',
    blogs: 'Блог',
    download: 'Завантажити',
    github: 'GitHub',
    darkMode: 'Темна тема',
    lightMode: 'Світла тема',
    downloadNow: 'Завантажити зараз',
    changeLanguage: 'Змінити мову',
    githubRepo: 'GitHub репозиторій',
    discordServer: 'Discord сервер',
    selectLanguage: 'Виберіть мову',
    language: 'Мова',
    about: 'Про нас',
    contact: 'Контакти',
    contactUs: 'Зв\'язатися з нами',
    email: 'Електронна пошта',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Підтримати нас',
    joinCommunity: 'Приєднатися до спільноти',
    communityPlatforms: 'Платформи спільноти',
    resources: 'Ресурси',
    support: 'Підтримка',
    documentation: 'Документація',
    blogPosts: 'Записи блогу',
    privacyPolicy: 'Політика конфіденційності',
    error404: 'Помилка 404',
    pageNotFound: 'Сторінку не знайдено',
    backToHome: 'Повернутися на головну',
    homeMessage: 'Вибачте, сторінка, яку ви шукаєте, не існує.',
    search: 'Пошук',
    submit: 'Надіслати'
  },
  zh: {
    guide: '文档',
    guideLocal: '指南',
    privacy: '隐私政策',
    changelogs: '更新日志',
    blogs: '博客',
    download: '下载',
    github: 'GitHub',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    downloadNow: '立即下载',
    changeLanguage: '更改语言',
    githubRepo: 'GitHub 仓库',
    discordServer: 'Discord 服务器',
    selectLanguage: '选择语言',
    language: '语言',
    about: '关于我们',
    contact: '联系我们',
    contactUs: '联系我们',
    email: '电子邮件',
    patreon: 'Patreon',
    afdian: 'Afdian 爱发电',
    kook: 'Kook',
    supportUs: '支持我们',
    joinCommunity: '加入我们的社区',
    communityPlatforms: '社区平台',
    resources: '资源',
    support: '支持',
    documentation: '文档',
    blogPosts: '博客文章',
    privacyPolicy: '隐私政策',
    error404: '404 错误',
    pageNotFound: '找不到页面',
    backToHome: '返回首页',
    homeMessage: '抱歉，您查找的页面不存在。',
    search: '搜索',
    submit: '提交'
  },
  de: {
    guide: 'Dokumentation',
    guideLocal: 'Anleitung',
    privacy: 'Datenschutz',
    changelogs: 'Änderungsprotokoll',
    blogs: 'Blog',
    download: 'Herunterladen',
    github: 'GitHub',
    darkMode: 'Dunkler Modus',
    lightMode: 'Heller Modus',
    downloadNow: 'Jetzt herunterladen',
    changeLanguage: 'Sprache ändern',
    githubRepo: 'GitHub-Repository',
    discordServer: 'Discord-Server',
    selectLanguage: 'Sprache auswählen',
    language: 'Sprache',
    about: 'Über uns',
    contact: 'Kontakt',
    contactUs: 'Kontaktieren Sie uns',
    email: 'E-Mail',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: 'Unterstützen Sie uns',
    joinCommunity: 'Treten Sie unserer Community bei',
    communityPlatforms: 'Community-Plattformen',
    resources: 'Ressourcen',
    support: 'Support',
    documentation: 'Dokumentation',
    blogPosts: 'Blogbeiträge',
    privacyPolicy: 'Datenschutzrichtlinie',
    error404: '404 Fehler',
    pageNotFound: 'Seite nicht gefunden',
    backToHome: 'Zurück zur Startseite',
    homeMessage: 'Entschuldigung, die gesuchte Seite existiert nicht.',
    search: 'Suchen',
    submit: 'Absenden'
  },
  ja: {
    guide: 'ドキュメント',
    guideLocal: 'ガイド',
    privacy: 'プライバシーポリシー',
    changelogs: '更新履歴',
    blogs: 'ブログ',
    download: 'ダウンロード',
    github: 'GitHub',
    darkMode: 'ダークモード',
    lightMode: 'ライトモード',
    downloadNow: '今すぐダウンロード',
    changeLanguage: '言語を変更',
    githubRepo: 'GitHubリポジトリ',
    discordServer: 'Discordサーバー',
    selectLanguage: '言語を選択',
    language: '言語',
    about: '私たちについて',
    contact: 'お問い合わせ',
    contactUs: 'お問い合わせ',
    email: 'メール',
    patreon: 'Patreon',
    afdian: 'Afdian',
    kook: 'Kook',
    supportUs: '私たちをサポート',
    joinCommunity: 'コミュニティに参加',
    communityPlatforms: 'コミュニティプラットフォーム',
    resources: 'リソース',
    support: 'サポート',
    documentation: 'ドキュメント',
    blogPosts: 'ブログ記事',
    privacyPolicy: 'プライバシーポリシー',
    error404: '404エラー',
    pageNotFound: 'ページが見つかりません',
    backToHome: 'ホームに戻る',
    homeMessage: '申し訳ありませんが、お探しのページは存在しません。',
    search: '検索',
    submit: '送信'
  }
};
