
import React from "react";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { NoteAlert } from "../GuideAlerts";
import { CodeBlock } from "../CodeBlock";

export function DataStorageGuide() {
  return (
    <div className="space-y-8">
      <h2 className="text-3xl font-bold mb-6">Data Storage</h2>
      <p>XMCL data is divided into two parts:</p>
      <ul className="list-disc pl-6 space-y-2">
        <li>XMCL as a cache and database generated by chromium</li>
        <li>Minecraft related data</li>
      </ul>
      
      <section className="space-y-4">
        <h3 className="text-2xl font-bold">XMCL cache and database</h3>
        <p>The cache related to XMCL itself is stored in the system appdata path, which is different on different platforms.</p>
        
        <Tabs defaultValue="windows" className="w-full mb-6">
          <TabsList className="grid grid-cols-4 mb-4">
            <TabsTrigger value="windows" tooltip="Windows storage location">Windows</TabsTrigger>
            <TabsTrigger value="appx" tooltip="Windows APPX storage location">Windows (APPX)</TabsTrigger>
            <TabsTrigger value="macos" tooltip="macOS storage location">macOS</TabsTrigger>
            <TabsTrigger value="linux" tooltip="Linux storage location">Linux</TabsTrigger>
          </TabsList>
          <TabsContent value="windows" className="p-4 bg-black/30 rounded-lg">
            <CodeBlock>%AppData%\xmcl</CodeBlock>
          </TabsContent>
          <TabsContent value="appx" className="p-4 bg-black/30 rounded-lg">
            <p>The location is managed by Windows and may vary between versions.</p>
          </TabsContent>
          <TabsContent value="macos" className="p-4 bg-black/30 rounded-lg">
            <p>Standard macOS Application Support directory.</p>
          </TabsContent>
          <TabsContent value="linux" className="p-4 bg-black/30 rounded-lg">
            <p>Standard Linux data directory.</p>
          </TabsContent>
        </Tabs>
        
        <NoteAlert>
          Do not delete the files here unless you know what you are doing.
        </NoteAlert>
        
        <p>Here you will find some json files used to store various configurations, and the database will also be stored here.</p>
        
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>User data.</strong> Stores users' accounts, skin links, etc. Stored in the /user.json file.</li>
          <li><strong>Instance data.</strong> Stores instance configurations, such as Java path, memory allocation, etc. Stored in the /instances.json file.</li>
          <li><strong>Resource database.</strong> Metadata for resource files, such as parsed mod information. Stored in leveldb format, in the /resources-v2 folder.</li>
        </ul>
      </section>

      <Separator className="my-8 bg-white/10" />
      
      <section className="space-y-4">
        <h3 className="text-2xl font-bold">Minecraft related data</h3>
        <p>Minecraft related data is stored in the .minecraft folder, which is located in the following path:</p>
        
        <Tabs defaultValue="windows" className="w-full mb-6">
          <TabsList className="grid grid-cols-3 mb-4">
            <TabsTrigger value="windows" tooltip="Windows Minecraft data location">Windows</TabsTrigger>
            <TabsTrigger value="macos" tooltip="macOS Minecraft data location">macOS</TabsTrigger>
            <TabsTrigger value="linux" tooltip="Linux Minecraft data location">Linux</TabsTrigger>
          </TabsList>
          <TabsContent value="windows" className="p-4 bg-black/30 rounded-lg">
            <CodeBlock>%AppData%\.minecraft</CodeBlock>
          </TabsContent>
          <TabsContent value="macos" className="p-4 bg-black/30 rounded-lg">
            <CodeBlock>~/Library/Application Support/minecraft</CodeBlock>
          </TabsContent>
          <TabsContent value="linux" className="p-4 bg-black/30 rounded-lg">
            <CodeBlock>~/.minecraft</CodeBlock>
          </TabsContent>
        </Tabs>
        
        <p>This is the default location, but you can change it in the settings. If you have multiple instances, each instance can have its own .minecraft folder.</p>
      </section>
    </div>
  );
}
