import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertCircle } from "lucide-react";
import { UnderConstructionBadge } from "../GuideBages";
import { CodeBlock } from "../CodeBlock";

export function DataStorageGuide() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-8">
        <h2 className="text-3xl font-bold tracking-tight">Data Storage</h2>
        <UnderConstructionBadge></UnderConstructionBadge>
      </div>

      <Card className="mb-8 border border-white/10 bg-black/20 backdrop-blur-sm">
        <CardHeader>
          <CardTitle className="text-2xl font-semibold">Overview</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p>XMCL data is divided into two parts:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>XMCL as a cache and database generated by chromium</li>
            <li>Minecraft related data</li>
          </ul>
        </CardContent>
      </Card>

      <Card className="mb-8 border border-white/10 bg-black/20 backdrop-blur-sm">
        <CardHeader>
          <CardTitle className="text-2xl font-semibold">
            XMCL cache and database
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p>
            The cache related to XMCL itself is stored in the system appdata
            path, which is different on different platforms.
          </p>

          <Tabs defaultValue="windows" className="w-full">
            <TabsList className="grid w-full grid-cols-4 mb-6 rounded-lg bg-slate-800/50">
              <TabsTrigger value="windows" className="rounded-md">
                Windows
              </TabsTrigger>
              <TabsTrigger value="appx" className="rounded-md">
                Windows (APPX)
              </TabsTrigger>
              <TabsTrigger value="macos" className="rounded-md">
                macOS
              </TabsTrigger>
              <TabsTrigger value="linux" className="rounded-md">
                Linux
              </TabsTrigger>
            </TabsList>
            <TabsContent value="windows" className="space-y-4 mt-2">
              <CodeBlock>%AppData%\xmcl</CodeBlock>
            </TabsContent>
            <TabsContent value="appx" className="space-y-4 mt-2">
              <CodeBlock>
                %LocalAppData%\Packages\XMCL_68mcaawk44tpj\LocalCache\Roaming\xmcl
              </CodeBlock>
            </TabsContent>
            <TabsContent value="macos" className="space-y-4 mt-2">
              <CodeBlock>~/Library/Application Support/xmcl</CodeBlock>
            </TabsContent>
            <TabsContent value="linux" className="space-y-4 mt-2">
              <CodeBlock>~/.config/xmcl</CodeBlock>
            </TabsContent>
          </Tabs>

          <div className="flex items-start gap-3 bg-amber-500/10 p-4 rounded-lg border border-amber-300/20">
            <AlertCircle className="h-5 w-5 text-amber-300 mt-0.5" />
            <div>
              <strong className="text-amber-300">Warning:</strong> Do not delete
              the files here unless you know what you are doing.
            </div>
          </div>

          <p>
            Here you will find some json files used to store various
            configurations, and the database will also be stored here.
          </p>

          <ul className="list-disc pl-6 space-y-2 text-slate-200">
            <li>
              <strong>User data.</strong> Stores users' accounts, skin links,
              etc. Stored in the /user.json file.
            </li>
            <li>
              <strong>Global settings.</strong> Global settings, such as
              language, proxy URL, download node, etc. Stored in the
              /settings.json file.
            </li>
            <li>
              <strong>Instance cache.</strong> Records the last selected
              instance path and the paths of all known instances. Stored in the
              /instances.json file.
            </li>
            <li>
              <strong>Java cache.</strong> Records detected Java paths, version
              information, etc. Stored in the /java.json file.
            </li>
            <li>
              <strong>Resource database.</strong> Metadata for resource files,
              such as parsed mod information. Stored in leveldb format, in the
              /resources-v2 folder.
            </li>
            <li>
              <strong>Logs.</strong> XMCL historical logs. Stored in the /logs
              folder.
            </li>
          </ul>
        </CardContent>
      </Card>

      <Card className="border border-white/10 bg-black/20 backdrop-blur-sm">
        <CardHeader>
          <CardTitle className="text-2xl font-semibold">
            Minecraft-related data
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-slate-200">
            I believe you are very familiar with the directory structure of
            Minecraft data. The data directory of XMCL is slightly different
            from that of Minecraft:
          </p>

          <CodeBlock language="markdown">
            {'"Private Data folder"\n' +
              "└─ 📂mods # Private mods folder for each instance\n" +
              "└─ 📂resourcepacks # Private resourcepacks folder for each instance\n" +
              "└─ 📂shaderpacks # Private shaderpacks folder for each instance\n" +
              "└─ 📂versions # Private versions folder for each instance\n" +
              "└─ 📂assets # Private assets folder for each instance\n" +
              "└─ 📂libraries # Private libraries folder for each instance\n" +
              "└─ 📂instances # Contains the instances created by XMCL"}
          </CodeBlock>

          <p className="text-slate-200">
            Most of the content is actually the same as Minecraft, among which
            the instances folder contains all instance files.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
