
import React from "react";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { NoteAlert } from "../GuideAlerts";
import { CodeBlock } from "../CodeBlock";

export function DataStorageGuide() {
  return (
    <div className="space-y-8">
      <h2 className="text-3xl font-bold mb-6">Data Storage</h2>
      <p>XMCL data is divided into two parts:</p>
      <ul className="list-disc pl-6 space-y-2">
        <li>XMCL as a cache and database generated by chromium</li>
        <li>Minecraft related data</li>
      </ul>
      
      <section className="space-y-4">
        <h3 className="text-2xl font-bold">XMCL cache and database</h3>
        <p>The cache related to XMCL itself is stored in the system appdata path, which is different on different platforms.</p>
        
        <Tabs defaultValue="windows" className="w-full mb-6">
          <TabsList className="grid grid-cols-4 mb-4">
            <TabsTrigger value="windows">Windows</TabsTrigger>
            <TabsTrigger value="appx">Windows (APPX)</TabsTrigger>
            <TabsTrigger value="macos">macOS</TabsTrigger>
            <TabsTrigger value="linux">Linux</TabsTrigger>
          </TabsList>
          <TabsContent value="windows" className="p-4 bg-black/30 rounded-lg">
            <CodeBlock>%AppData%\xmcl</CodeBlock>
          </TabsContent>
          <TabsContent value="appx" className="p-4 bg-black/30 rounded-lg">
            <p>The location is managed by Windows and may vary between versions.</p>
          </TabsContent>
          <TabsContent value="macos" className="p-4 bg-black/30 rounded-lg">
            <p>Standard macOS Application Support directory.</p>
          </TabsContent>
          <TabsContent value="linux" className="p-4 bg-black/30 rounded-lg">
            <p>Standard Linux data directory.</p>
          </TabsContent>
        </Tabs>
        
        <NoteAlert>
          Do not delete the files here unless you know what you are doing.
        </NoteAlert>
        
        <p>Here you will find some json files used to store various configurations, and the database will also be stored here.</p>
        
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>User data.</strong> Stores users' accounts, skin links, etc. Stored in the /user.json file.</li>
          <li><strong>Global settings.</strong> Global settings, such as language, proxy URL, download node, etc. Stored in the /settings.json file.</li>
          <li><strong>Instance cache.</strong> Records the last selected instance path and the paths of all known instances. Stored in the /instances.json file.</li>
          <li><strong>Java cache.</strong> Records detected Java paths, version information, etc. Stored in the /java.json file.</li>
          <li><strong>Resource database.</strong> Metadata for resource files, such as parsed mod information. Stored in leveldb format, in the /resources-v2 folder.</li>
          <li><strong>Logs.</strong> XMCL historical logs. Stored in the /logs folder.</li>
        </ul>
      </section>

      <Separator className="my-8 bg-white/10" />
      
      <section className="space-y-4">
        <h3 className="text-2xl font-bold">Minecraft-related data</h3>
        <p>I believe you are very familiar with the directory structure of Minecraft data. The data directory of XMCL is slightly different from that of Minecraft:</p>
        
        <CodeBlock>
{`"Public Data folder"
└─ 📂mods # Shared mods folder for all instances
  └─ modA.jar # A specific mod file, instance might link mods from it.
├─ 📂resourcepacks # Shared resourcepacks folder for all instances
├─ 📂shaderpacks # Shared shaderpacks folder for all instances
├─ 📂versions # Shared versions folder for all instances
├─ 📂assets # Shared assets folder for all instances
├─ 📂libraries # Shared libraries folder for all instances
└─ 📂instances # Contains the instances created by XMCL`}
        </CodeBlock>
        
        <p>Most of the content is actually the same as Minecraft, among which the instances folder contains all instance files.</p>
      </section>
    </div>
  );
}
